# Generated by Django 3.1.5 on 2021-04-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=9)),
                ('carrera', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
